version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r src/requirements.txt -t output/
  build:
    commands:
      - echo Copying source files...
      - cp src/index.py output/
artifacts:
  files:
    - '**/*'
  base-directory: output
